// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxbwnbzaydgldkkdckvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4YnduYnpheWRnbGRra2Rja3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjgxOTksImV4cCI6MjA3MzQ0NDE5OX0.pQkvTLuRYmk6mWyLPp6QtB8Er0OPNSwMndz25j3JrKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});